FROM node:14.17-alpine as build

LABEL decription="Development image for KitchenFarmr."

HEALTHCHECK --interval=1m --timeout=5s --retries=2 \
    CMD curl -f http://localhost:3000 || exit 1

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]