name: Test

on:
  push:
    branches-ignore:
      - 'production'
    paths-ignore:
      - '**.md'
      - 'Makefile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint with Eslint
        run: |
          npm run lint

      - name: Test with Mocha & Chai
        run: |
          npm run coverage

      # - name: Notify slack success
      #   if: success()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     status: SUCCESS
      #     color: good

      # - name: Notify slack fail
      #   if: failure()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     status: FAILED
      #     color: danger
